<Project>    
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <AnalysisLevel>latest</AnalysisLevel>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        
        <!-- Nuget Global Metadata -->
        <Authors>DevSource Team</Authors>
        <Company>DevSource</Company>
        <RepositoryUrl>https://github.com/Devsourceio/devsource-dispatcher</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        
        <!-- Packing -->
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>
</Project>