using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace DevSource.Dispatcher.SourceGenerator;

/// <summary>
/// Represents a source generator that facilitates the generation of implementation code for the dispatcher pattern.
/// This generator analyzes the syntax tree and semantic model of C# code to identify handler types
/// and generates optimized dispatching logic for command, query, and notification handlers.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class DispatcherSourceGenerator : IIncrementalGenerator
{
  internal const string CommandHandlerMetadataName = "DevSource.Dispatcher.Commands.ICommandHandler`1";
  internal const string CommandHandlerWithResponseMetadataName = "DevSource.Dispatcher.Commands.ICommandHandler`2";
  internal const string QueryHandlerMetadataName = "DevSource.Dispatcher.Queries.IQueryHandler`2";
  internal const string NotificationHandlerMetadataName = "DevSource.Dispatcher.Notifications.INotificationHandler`1";

  /// <summary>
  /// Initializes the incremental source generator by configuring the context to register syntax providers
  /// and source output, facilitating the generation of dispatcher-related code.
  /// </summary>
  /// <param name="context">
  /// The incremental generator initialization context, which provides methods to register syntax receivers
  /// and source production pipelines.
  /// </param>
  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    var compilationAndTypes = context.SyntaxProvider
        .CreateSyntaxProvider(
            static (node, _) => node is ClassDeclarationSyntax,
            static (generatorContext, _) => generatorContext.SemanticModel.GetDeclaredSymbol(generatorContext.Node) as INamedTypeSymbol)
        .Where(static symbol => symbol is not null)
        .Collect()
        .Combine(context.CompilationProvider);

    context.RegisterSourceOutput(compilationAndTypes, static (productionContext, source) =>
    {
      var types = source.Left;
      var compilation = source.Right;

      var model = DispatcherGenerationModel.Create(compilation, types);
      var generatedCode = RenderGeneratedDispatcher(model);

      productionContext.AddSource("GeneratedDispatcher.g.cs", SourceText.From(generatedCode, Encoding.UTF8));
    });
  }

  private static string RenderGeneratedDispatcher(DispatcherGenerationModel model)
  {
    var builder = new StringBuilder();
    builder.AppendLine("// <auto-generated />");
    builder.AppendLine("#nullable enable");
    builder.AppendLine("using System;");
    builder.AppendLine("using System.Threading;");
    builder.AppendLine("using System.Threading.Tasks;");
    builder.AppendLine("using DevSource.Dispatcher.Commands;");
    builder.AppendLine("using DevSource.Dispatcher.Engine;");
    builder.AppendLine("using DevSource.Dispatcher.Notifications;");
    builder.AppendLine("using DevSource.Dispatcher.Queries;");
    builder.AppendLine();
    if (model.HasHandlers)
    {
      builder.AppendLine("[assembly: DevSource.Dispatcher.DispatcherAssemblyAttribute]");
      builder.AppendLine();
    }
    builder.AppendLine("namespace DevSource.Dispatcher.Generated;");
    builder.AppendLine();
    builder.AppendLine("public sealed class GeneratedDispatcher : IGeneratedDispatcher");
    builder.AppendLine("{");
    builder.AppendLine("    private readonly IRequestHandlerResolver _handlerResolver;");
    builder.AppendLine();
    builder.AppendLine("    private static TResponse CastResponse<TResponse>(object? response)");
    builder.AppendLine("        => (TResponse)response!;");
    builder.AppendLine();
    builder.AppendLine("    public GeneratedDispatcher(IRequestHandlerResolver handlerResolver)");
    builder.AppendLine("    {");
    builder.AppendLine("        _handlerResolver = handlerResolver ?? throw new ArgumentNullException(nameof(handlerResolver));");
    builder.AppendLine("    }");
    builder.AppendLine();
    builder.AppendLine("    public GeneratedDispatcher(IServiceProvider serviceProvider)");
    builder.AppendLine("        : this(new ServiceProviderRequestHandlerResolver(serviceProvider))");
    builder.AppendLine("    {");
    builder.AppendLine("    }");
    builder.AppendLine();
    RenderCommandMethod(builder, model.CommandRequests, model.CommandRequestsWithResponse);
    builder.AppendLine();
    RenderQueryMethod(builder, model.QueryRequests);
    builder.AppendLine();
    RenderNotificationMethod(builder, model.NotificationRequests);
    builder.AppendLine("}");
    return builder.ToString();
  }

  private static void RenderCommandMethod(StringBuilder builder, ImmutableArray<string> commandRequests, ImmutableArray<RequestWithResponseModel> commandRequestsWithResponse)
  {
    builder.AppendLine("    async ValueTask<bool> IGeneratedCommandDispatcher.TryDispatchAsync<TCommand>(TCommand command, CancellationToken cancellationToken)");
    builder.AppendLine("    {");
    builder.AppendLine("        if (command is null)");
    builder.AppendLine("            throw new ArgumentNullException(nameof(command));");
    builder.AppendLine();

    for (var index = 0; index < commandRequests.Length; index++)
    {
      var requestType = commandRequests[index];
      var variableName = $"typedCommand{index}";
      builder.AppendLine($"        if (command is {requestType} {variableName})");
      builder.AppendLine("        {");
      builder.AppendLine($"            await GeneratedDispatchExecutor.ExecuteCommandAsync(_handlerResolver, {variableName}, cancellationToken).ConfigureAwait(false);");
      builder.AppendLine("            return true;");
      builder.AppendLine("        }");
      builder.AppendLine();
    }

    builder.AppendLine("        return false;");
    builder.AppendLine("    }");
    builder.AppendLine();
    builder.AppendLine("    async ValueTask<DispatchResult<TResponse>> IGeneratedCommandDispatcher.TryDispatchAsync<TCommand, TResponse>(TCommand command, CancellationToken cancellationToken)");
    builder.AppendLine("    {");
    builder.AppendLine("        if (command is null)");
    builder.AppendLine("            throw new ArgumentNullException(nameof(command));");
    builder.AppendLine();

    for (var index = 0; index < commandRequestsWithResponse.Length; index++)
    {
      var request = commandRequestsWithResponse[index];
      var variableName = $"typedCommand{index}";
      builder.AppendLine($"        if (command is {request.RequestType} {variableName})");
      builder.AppendLine("        {");
      builder.AppendLine($"            var response = await GeneratedDispatchExecutor.ExecuteCommandAsync<{request.RequestType}, {request.ResponseType}>(_handlerResolver, {variableName}, cancellationToken).ConfigureAwait(false);");
      builder.AppendLine("            return DispatchResult<TResponse>.Handled(CastResponse<TResponse>(response));");
      builder.AppendLine("        }");
      builder.AppendLine();
    }

    builder.AppendLine("        return DispatchResult<TResponse>.NotHandled();");
    builder.AppendLine("    }");
  }

  private static void RenderQueryMethod(StringBuilder builder, ImmutableArray<RequestWithResponseModel> queryRequests)
  {
    builder.AppendLine("    async ValueTask<DispatchResult<TResponse>> IGeneratedQueryDispatcher.TryDispatchAsync<TQuery, TResponse>(TQuery query, CancellationToken cancellationToken)");
    builder.AppendLine("    {");
    builder.AppendLine("        if (query is null)");
    builder.AppendLine("            throw new ArgumentNullException(nameof(query));");
    builder.AppendLine();

    for (var index = 0; index < queryRequests.Length; index++)
    {
      var request = queryRequests[index];
      var variableName = $"typedQuery{index}";
      builder.AppendLine($"        if (query is {request.RequestType} {variableName})");
      builder.AppendLine("        {");
      builder.AppendLine($"            var response = await GeneratedDispatchExecutor.ExecuteQueryAsync<{request.RequestType}, {request.ResponseType}>(_handlerResolver, {variableName}, cancellationToken).ConfigureAwait(false);");
      builder.AppendLine("            return DispatchResult<TResponse>.Handled(CastResponse<TResponse>(response));");
      builder.AppendLine("        }");
      builder.AppendLine();
    }

    builder.AppendLine("        return DispatchResult<TResponse>.NotHandled();");
    builder.AppendLine("    }");
  }

  private static void RenderNotificationMethod(StringBuilder builder, ImmutableArray<string> notificationRequests)
  {
    builder.AppendLine("    async ValueTask<bool> IGeneratedNotificationDispatcher.TryPublishAsync<TNotification>(TNotification notification, CancellationToken cancellationToken)");
    builder.AppendLine("    {");
    builder.AppendLine("        if (notification is null)");
    builder.AppendLine("            throw new ArgumentNullException(nameof(notification));");
    builder.AppendLine();

    for (var index = 0; index < notificationRequests.Length; index++)
    {
      var requestType = notificationRequests[index];
      var variableName = $"typedNotification{index}";
      builder.AppendLine($"        if (notification is {requestType} {variableName})");
      builder.AppendLine("        {");
      builder.AppendLine($"            await GeneratedDispatchExecutor.PublishNotificationAsync(_handlerResolver, {variableName}, cancellationToken).ConfigureAwait(false);");
      builder.AppendLine("            return true;");
      builder.AppendLine("        }");
      builder.AppendLine();
    }

    builder.AppendLine("        return false;");
    builder.AppendLine("    }");
  }
}

internal sealed class DispatcherGenerationModel
{
  public DispatcherGenerationModel(
      ImmutableArray<string> commandRequests,
      ImmutableArray<RequestWithResponseModel> commandRequestsWithResponse,
      ImmutableArray<RequestWithResponseModel> queryRequests,
      ImmutableArray<string> notificationRequests)
  {
    CommandRequests = commandRequests;
    CommandRequestsWithResponse = commandRequestsWithResponse;
    QueryRequests = queryRequests;
    NotificationRequests = notificationRequests;
  }

  public ImmutableArray<string> CommandRequests { get; }

  public ImmutableArray<RequestWithResponseModel> CommandRequestsWithResponse { get; }

  public ImmutableArray<RequestWithResponseModel> QueryRequests { get; }

  public ImmutableArray<string> NotificationRequests { get; }

  public bool HasHandlers
      => !CommandRequests.IsEmpty || !CommandRequestsWithResponse.IsEmpty || !QueryRequests.IsEmpty || !NotificationRequests.IsEmpty;

  public static DispatcherGenerationModel Create(Compilation compilation, ImmutableArray<INamedTypeSymbol?> candidateTypes)
  {
    var commandHandlerSymbol = compilation.GetTypeByMetadataName(DispatcherSourceGenerator.CommandHandlerMetadataName);
    var commandHandlerWithResponseSymbol = compilation.GetTypeByMetadataName(DispatcherSourceGenerator.CommandHandlerWithResponseMetadataName);
    var queryHandlerSymbol = compilation.GetTypeByMetadataName(DispatcherSourceGenerator.QueryHandlerMetadataName);
    var notificationHandlerSymbol = compilation.GetTypeByMetadataName(DispatcherSourceGenerator.NotificationHandlerMetadataName);

    var commandRequests = ImmutableSortedSet.CreateBuilder<string>(StringComparer.Ordinal);
    var commandRequestsWithResponse = ImmutableDictionary.CreateBuilder<string, string>(StringComparer.Ordinal);
    var queryRequests = ImmutableDictionary.CreateBuilder<string, string>(StringComparer.Ordinal);
    var notificationRequests = ImmutableSortedSet.CreateBuilder<string>(StringComparer.Ordinal);

    foreach (var type in candidateTypes)
    {
      if (type is null || type.IsAbstract)
        continue;

      foreach (var implementedInterface in type.AllInterfaces)
      {
        if (!implementedInterface.IsGenericType)
          continue;

        if (commandHandlerSymbol is not null && SymbolEqualityComparer.Default.Equals(implementedInterface.OriginalDefinition, commandHandlerSymbol))
        {
          commandRequests.Add(GetTypeName(implementedInterface.TypeArguments[0]));
          continue;
        }

        if (commandHandlerWithResponseSymbol is not null && SymbolEqualityComparer.Default.Equals(implementedInterface.OriginalDefinition, commandHandlerWithResponseSymbol))
        {
          commandRequestsWithResponse[GetTypeName(implementedInterface.TypeArguments[0])] = GetTypeName(implementedInterface.TypeArguments[1]);
          continue;
        }

        if (queryHandlerSymbol is not null && SymbolEqualityComparer.Default.Equals(implementedInterface.OriginalDefinition, queryHandlerSymbol))
        {
          queryRequests[GetTypeName(implementedInterface.TypeArguments[0])] = GetTypeName(implementedInterface.TypeArguments[1]);
          continue;
        }

        if (notificationHandlerSymbol is not null && SymbolEqualityComparer.Default.Equals(implementedInterface.OriginalDefinition, notificationHandlerSymbol))
          notificationRequests.Add(GetTypeName(implementedInterface.TypeArguments[0]));
      }
    }

    return new DispatcherGenerationModel(
        commandRequests.ToImmutable().ToImmutableArray(),
        commandRequestsWithResponse.Select(static pair => new RequestWithResponseModel(pair.Key, pair.Value)).ToImmutableArray(),
        queryRequests.Select(static pair => new RequestWithResponseModel(pair.Key, pair.Value)).ToImmutableArray(),
        notificationRequests.ToImmutable().ToImmutableArray());
  }

  private static string GetTypeName(ITypeSymbol symbol)
      => symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
          SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier |
          SymbolDisplayMiscellaneousOptions.UseSpecialTypes |
          SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers));
}
