using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace DevSource.Dispatcher.SourceGenerator;

/// <summary>
/// Source generator that generates a dispatcher implementation based on the command, query, and notification handler 
/// implementations found in the compilation.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class DispatcherSourceGenerator : IIncrementalGenerator
{
    internal const string CommandHandlerMetadataName = "DevSource.Dispatcher.Commands.ICommandHandler`1";
    internal const string CommandHandlerWithResponseMetadataName = "DevSource.Dispatcher.Commands.ICommandHandler`2";
    internal const string QueryHandlerMetadataName = "DevSource.Dispatcher.Queries.IQueryHandler`2";
    internal const string NotificationHandlerMetadataName = "DevSource.Dispatcher.Notifications.INotificationHandler`1";
    internal const string CommandPipelineBehaviorMetadataName = "DevSource.Dispatcher.IPipelineBehavior`1";
    internal const string PipelineBehaviorMetadataName = "DevSource.Dispatcher.IPipelineBehavior`2";

    /// <summary>
    /// Initializes the source generator by registering a syntax provider that looks for class declarations and collects their symbols.
    /// </summary>
    /// <param name="context">The initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var compilationAndTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax,
                static (generatorContext, _) => generatorContext.SemanticModel.GetDeclaredSymbol(generatorContext.Node) as INamedTypeSymbol)
            .Where(static symbol => symbol is not null)
            .Collect()
            .Combine(context.CompilationProvider);

        context.RegisterSourceOutput(compilationAndTypes, static (productionContext, source) =>
        {
            var types = source.Left;
            var compilation = source.Right;

            var model = DispatcherGenerationModel.Create(compilation, types);
            var generatedCode = RenderGeneratedDispatcher(model);
            var generatedRegistrationCode = RenderGeneratedRegistrationExtensions(model);

            productionContext.AddSource("GeneratedDispatcher.g.cs", SourceText.From(generatedCode, Encoding.UTF8));
            productionContext.AddSource("GeneratedServiceCollectionExtensions.g.cs", SourceText.From(generatedRegistrationCode, Encoding.UTF8));
        });
    }

    private static string RenderGeneratedDispatcher(DispatcherGenerationModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Threading;");
        builder.AppendLine("using System.Threading.Tasks;");
        builder.AppendLine("using DevSource.Dispatcher.Commands;");
        builder.AppendLine("using DevSource.Dispatcher.Engine;");
        builder.AppendLine("using DevSource.Dispatcher.Notifications;");
        builder.AppendLine("using DevSource.Dispatcher.Queries;");
        builder.AppendLine();
        builder.AppendLine("namespace DevSource.Dispatcher.Generated;");
        builder.AppendLine();
        builder.AppendLine("public sealed class GeneratedDispatcher : IGeneratedDispatcher");
        builder.AppendLine("{");
        builder.AppendLine("    private readonly IRequestHandlerResolver _handlerResolver;");
        builder.AppendLine();
        builder.AppendLine("    public GeneratedDispatcher(IRequestHandlerResolver handlerResolver)");
        builder.AppendLine("    {");
        builder.AppendLine("        _handlerResolver = handlerResolver ?? throw new ArgumentNullException(nameof(handlerResolver));");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public GeneratedDispatcher(IServiceProvider serviceProvider)");
        builder.AppendLine("        : this(new ServiceProviderRequestHandlerResolver(serviceProvider))");
        builder.AppendLine("    {");
        builder.AppendLine("    }");
        builder.AppendLine();
        RenderCommandMethod(builder, model.CommandRequests, model.CommandRequestsWithResponse);
        builder.AppendLine();
        RenderQueryMethod(builder, model.QueryRequests);
        builder.AppendLine();
        RenderNotificationMethod(builder, model.NotificationRequests);
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string RenderGeneratedRegistrationExtensions(DispatcherGenerationModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine("using DevSource.Dispatcher.Engine;");
        builder.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        builder.AppendLine();
        builder.AppendLine("namespace DevSource.Dispatcher.Generated;");
        builder.AppendLine();
        builder.AppendLine("public static class GeneratedServiceCollectionExtensions");
        builder.AppendLine("{");
        builder.AppendLine("    public static IServiceCollection AddGeneratedDispatcher(this IServiceCollection services)");
        builder.AppendLine("    {");
        builder.AppendLine("        ArgumentNullException.ThrowIfNull(services);");
        builder.AppendLine();

        foreach (var registration in model.ServiceRegistrations)
        {
            builder.AppendLine(registration.IsOpenGeneric
                ? $"        services.AddTransient(typeof({registration.ServiceType}), typeof({registration.ImplementationType}));"
                : $"        services.AddTransient<{registration.ServiceType}, {registration.ImplementationType}>();");
        }

        if (model.ServiceRegistrations.Length > 0)
            builder.AppendLine();

        builder.AppendLine("        services.AddDispatcher<GeneratedDispatcher>();");
        builder.AppendLine("        return services;");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void RenderCommandMethod(StringBuilder builder, ImmutableArray<string> commandRequests, ImmutableArray<RequestWithResponseModel> commandRequestsWithResponse)
    {
        builder.AppendLine("    async ValueTask<bool> IGeneratedCommandDispatcher.TryDispatchAsync<TCommand>(TCommand command, CancellationToken cancellationToken)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (command is null)");
        builder.AppendLine("            throw new ArgumentNullException(nameof(command));");
        builder.AppendLine();

        for (var index = 0; index < commandRequests.Length; index++)
        {
            var requestType = commandRequests[index];
            var variableName = $"typedCommand{index}";
            builder.AppendLine($"        if (command is {requestType} {variableName})");
            builder.AppendLine("        {");
            builder.AppendLine($"            await GeneratedDispatchExecutor.ExecuteCommandAsync(_handlerResolver, {variableName}, cancellationToken).ConfigureAwait(false);");
            builder.AppendLine("            return true;");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        builder.AppendLine("        return false;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    async ValueTask<DispatchResult<TResponse>> IGeneratedCommandDispatcher.TryDispatchAsync<TCommand, TResponse>(TCommand command, CancellationToken cancellationToken)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (command is null)");
        builder.AppendLine("            throw new ArgumentNullException(nameof(command));");
        builder.AppendLine();

        for (var index = 0; index < commandRequestsWithResponse.Length; index++)
        {
            var request = commandRequestsWithResponse[index];
            var variableName = $"typedCommand{index}";
            builder.AppendLine($"        if (command is {request.RequestType} {variableName})");
            builder.AppendLine("        {");
            builder.AppendLine($"            var response = await GeneratedDispatchExecutor.ExecuteCommandAsync<{request.RequestType}, {request.ResponseType}>(_handlerResolver, {variableName}, cancellationToken).ConfigureAwait(false);");
            builder.AppendLine("            return DispatchResult<TResponse>.Handled((TResponse)(object)response!);");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        builder.AppendLine("        return DispatchResult<TResponse>.NotHandled();");
        builder.AppendLine("    }");
    }

    private static void RenderQueryMethod(StringBuilder builder, ImmutableArray<RequestWithResponseModel> queryRequests)
    {
        builder.AppendLine("    async ValueTask<DispatchResult<TResponse>> IGeneratedQueryDispatcher.TryDispatchAsync<TQuery, TResponse>(TQuery query, CancellationToken cancellationToken)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (query is null)");
        builder.AppendLine("            throw new ArgumentNullException(nameof(query));");
        builder.AppendLine();

        for (var index = 0; index < queryRequests.Length; index++)
        {
            var request = queryRequests[index];
            var variableName = $"typedQuery{index}";
            builder.AppendLine($"        if (query is {request.RequestType} {variableName})");
            builder.AppendLine("        {");
            builder.AppendLine($"            var response = await GeneratedDispatchExecutor.ExecuteQueryAsync<{request.RequestType}, {request.ResponseType}>(_handlerResolver, {variableName}, cancellationToken).ConfigureAwait(false);");
            builder.AppendLine("            return DispatchResult<TResponse>.Handled((TResponse)(object)response!);");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        builder.AppendLine("        return DispatchResult<TResponse>.NotHandled();");
        builder.AppendLine("    }");
    }

    private static void RenderNotificationMethod(StringBuilder builder, ImmutableArray<string> notificationRequests)
    {
        builder.AppendLine("    async ValueTask<bool> IGeneratedNotificationDispatcher.TryPublishAsync<TNotification>(TNotification notification, CancellationToken cancellationToken)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (notification is null)");
        builder.AppendLine("            throw new ArgumentNullException(nameof(notification));");
        builder.AppendLine();

        for (var index = 0; index < notificationRequests.Length; index++)
        {
            var requestType = notificationRequests[index];
            var variableName = $"typedNotification{index}";
            builder.AppendLine($"        if (notification is {requestType} {variableName})");
            builder.AppendLine("        {");
            builder.AppendLine($"            await GeneratedDispatchExecutor.PublishNotificationAsync(_handlerResolver, {variableName}, cancellationToken).ConfigureAwait(false);");
            builder.AppendLine("            return true;");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        builder.AppendLine("        return false;");
        builder.AppendLine("    }");
    }
}
