<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <IsPackable>true</IsPackable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>DevSource.Dispatcher</PackageId>
    <Title>DevSource.Dispatcher</Title>
    <Description>High-performance dispatcher for .NET with commands, queries, notifications, deterministic pipelines, runtime fallback, and source-generated dispatch.</Description>
    <PackageTags>dispatcher;cqrs;mediator;pipeline;source-generator;performance</PackageTags>
    <RepositoryUrl>https://github.com/uitanmaciel/devsource-dispatcher</RepositoryUrl>
    <PackageProjectUrl>https://github.com/uitanmaciel/devsource-dispatcher</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Authors>Uitan Maciel</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);IncludeEngineBuildOutput</TargetsForTfmSpecificBuildOutput>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);IncludeSourceGeneratorAnalyzer</TargetsForTfmSpecificContentInPackage>
    <Version>1.0.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <Target Name="BuildOnePackageArtifacts" BeforeTargets="Pack" Condition="'$(NoBuild)' != 'true'">
    <MSBuild Projects="..\DevSource.Dispatcher.Engine\DevSource.Dispatcher.Engine.csproj" Targets="Build" Properties="Configuration=$(Configuration)" />
    <MSBuild Projects="..\DevSource.Dispatcher.SourceGenerator\DevSource.Dispatcher.SourceGenerator.csproj" Targets="Build" Properties="Configuration=$(Configuration)" />
  </Target>

  <Target Name="IncludeEngineBuildOutput">
    <ItemGroup>
      <BuildOutputInPackage Include="..\DevSource.Dispatcher.Engine\bin\$(Configuration)\net10.0\DevSource.Dispatcher.Engine.dll">
        <TargetPath>DevSource.Dispatcher.Engine.dll</TargetPath>
      </BuildOutputInPackage>
    </ItemGroup>
  </Target>

  <Target Name="IncludeSourceGeneratorAnalyzer">
    <ItemGroup>
      <TfmSpecificPackageFile Include="..\DevSource.Dispatcher.SourceGenerator\bin\$(Configuration)\netstandard2.0\DevSource.Dispatcher.SourceGenerator.dll">
        <PackagePath>analyzers/dotnet/cs</PackagePath>
      </TfmSpecificPackageFile>
    </ItemGroup>
  </Target>

</Project>
